version: 2
jobs:
  build-and-start:
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: npm run start
  test:
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-start